"""
pop_norm_flu.py

We take flu hospitalization numbers and adjusts them by population size so we can
fairly compare different states. Without this adjustment, big states like CA would
always look worse than small states like Vermont just because of population difference.

This will Generate:
A CSV file with a new column called "hosps_pop_norm" that shows hospitalizations per 100,000
people. This makes it easy to compare flu severity across any state or region.

Input file needed:
- analysis_data/formatted_flu.csv (created by format_flu_data.py)

Output file created:
- analysis_data/hosps_pop_norm.csv

The math:
hosps_pop_norm = (raw hospitalizations) / (population / 100,000)
"""

import os
import pandas as pd

#File paths for Input & Output
IN_PATH = os.path.join("analysis_data", "formatted_flu.csv")
OUT_PATH = os.path.join("analysis_data", "hosps_pop_norm.csv")


def main():
    # Loading the formatted flu data
    # Checking if the input file exists before trying to open it
    if not os.path.exists(IN_PATH):
        raise FileNotFoundError(f"Input file not found: {IN_PATH}")
        
    # Read the CSV file that was generated by format_flu_data.py
    df = pd.read_csv(IN_PATH)

    #Checking columns
    required_cols = {"value", "population"}
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    # Normalize hospitalizations per 100k population
    df["hosps_pop_norm"] = df["value"] / (df["population"] / 100_000)

    df = df.sort_values(
        ["season", "location", "season_week"]
    ).reset_index(drop=True)

    df.to_csv(OUT_PATH, index=False)

    print(f"Wrote {OUT_PATH} with {len(df):,} rows.")
    print(
        "   hosps_pop_norm summary:",
        f"min={df['hosps_pop_norm'].min():.3f},",
        f"max={df['hosps_pop_norm'].max():.3f}",
    )


if __name__ == "__main__":
    main()
